api/main/blueprints/asset/__init__.py
from api.main.database import ASSET_TYPE_MAPPING, AssetTypes, ETFReplicationMethods
from api.main import db
from flask import Blueprint, render_template, redirect, url_for, flash
from api.main.blueprints.forms import AddAssetForm
from api.main.asset_scraper.scrapers import ASSET_TYPE_TO_SCRAPER_CLASS, ScraperConfig
from flask_marshmallow.sqla import SQLAlchemyAutoSchema
from sqlalchemy import select
from flask_login import login_required

asset = Blueprint("asset", __name__, url_prefix="/asset")


@asset.route("/add", methods=["GET", "POST"])
@login_required
def add_asset():
    form = AddAssetForm()
    if form.is_submitted():
        form.validate_on_submit()
        # flask-form returns from drop down list string
        # so its necessary to convert it to int to create AssetTypes enum instance.
        asset_type = AssetTypes(int(form.data["asset_type"]))
        try:
            asset_scraper = ASSET_TYPE_TO_SCRAPER_CLASS[asset_type].check_if_exists(
                ScraperConfig(asset_type), isin=form.data["isin"], query=form.data["ticker"]
            )
        except ValueError:
            isin, ticker = form.data["isin"], form.data["ticker"]
            flash(
                f"{asset_type.name} with ISIN: {isin}, ticker: {ticker}" + " does not exists!",
                "error",
            )
            form.isin.data = None
            form.ticker.data = None
            return render_template("add_asset.html", form=form)

        # asset_class = ASSET_TYPE_MAPPING[asset_type]["class"]
        asset_schema: SQLAlchemyAutoSchema = ASSET_TYPE_MAPPING[asset_type]["schema"]()

        asset_details = asset_scraper.scrape()
        replication = asset_details.pop("replication")
        asset_details["replication_method_id"] = db.session.scalar(
            select(ETFReplicationMethods.replication_method_id).where(
                ETFReplicationMethods.replication_method == replication
            )
        )

        if asset_details["replication_method_id"] is None:
            flash(f"Replication method {replication} does not exist in the database!", "error")
            return render_template("add_asset.html", form=form)

        new_asset = asset_schema.load(asset_details, transient=True)
        db.session.add(new_asset)
        db.session.commit()
        return redirect(url_for("index.profile"))

    return render_template("add_asset.html", form=form)

api/main/templates/add_asset.html
<!DOCTYPE html>
<html>
  <head>
    <title>Add Asset</title>
    <style>
      body {
        font-family: 'Roboto', Arial;
        background-color: #f2f2f2;
        font-size: 1rem;
      }
      h1 {
        text-align: center;
        color: #333;
        font-size: 35px;
      }
      form {
        background-color: #fff;
        border-radius: 5px;
        padding: 20px;
        width: 50%;
        margin: 0 auto;
      }
      label {
        display: block;
        margin-bottom: 5px;
        color: #333;
      }
      input[type="text"] {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-bottom: 10px;
      }
      input[type="submit"] {
        background-color: #4CAF50;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 6px;
        cursor: pointer;
      }
      input[type="submit"]:hover {
        background-color: #45a049;
      }
      .error {
        color: red;
      }
      label {
        font-size: 17px;
        font-weight: bold;
      }
      label[for="isin"], label[for="ticker"] {
        font-size: 18px;
        font-weight: bold;
      }
    </style>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&family=Roboto&display=swap" rel="stylesheet">
  </head>
  <body>
    <h1>Add Asset</h1>
    <form method="POST" action="{{ url_for('asset.add_asset') }}">
      {{ form.csrf_token }}
      <label for="asset_type">Asset Type:</label>
      {{ form.asset_type }}
      {% for error in form.asset_type.errors %}
        <p class="error">{{ error }}</p>
      {% endfor %}
      <br>
      <br>
      <label for="ticker">Ticker:</label>
      {{ form.ticker(size=20) }}
      {% for error in form.ticker.errors %}
        <p class="error">{{ error }}</p>
      {% endfor %}
      <label for="isin">ISIN:</label>
      {{ form.isin(size=30) }}
      {% for error in form.isin.errors %}
        <p class="error">{{ error }}</p>
      {% endfor %}
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          {% if category == 'error' %}
            <div class="error">{{ message }}</div>
          {% endif %}
        {% endfor %}
      {% endif %}
      {% endwith %}
      <br>
      <input type="submit" value="Add Asset">
    </form>
  </body>
</html>

api/main/templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio Manager</title>
    <style>
      body {
        font-family: 'Roboto', Arial;
        background-color: #f2f2f2;
        font-size: 1.5rem;
      }
      h1 {
        text-align: center;
        color: #333;
        font-size: 3rem;
        margin-top: 2rem;
      }
      p {
        font-size: 1.2rem;
        line-height: 1.5;
        margin-bottom: 1.5rem;
      }
      a {
        color: #4CAF50;
        text-decoration: none;
        font-weight: bold;
      }
      a:hover {
        text-decoration: underline;
      }
      form {
        background-color: #fff;
        border-radius: 5px;
        padding: 20px;
        width: 50%;
        margin: 0 auto;
      }
      label {
        display: block;
        margin-bottom: 5px;
        color: #333;
      }
      input[type="text"],
      input[type="password"],
      input[type="email"] {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-bottom: 10px;
      }
      input[type="submit"] {
        background-color: #4CAF50;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 6px;
        cursor: pointer;
      }
      input[type="submit"]:hover {
        background-color: #45a049;
      }
      .error {
        color: red;
      }
    </style>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&family=Roboto&display=swap" rel="stylesheet">
  </head>
  <body>
    <h1>Portfolio Manager</h1>
    <p>Welcome to Portfolio Manager! This web application allows you to keep track of your various investment assets.</p>
    <p>To get started, please <a href="{{ url_for('auth.register') }}">register</a> or <a href="{{ url_for('auth.login') }}">login</a>.</p>
    {% if current_user.is_authenticated %}
    <a href="{{ url_for('auth.logout')}} "> logout  {{ current_user.username }}</a>
    {% else %}
    <footer>Hi {{ current_user.username }}!</footer>
    {% endif %}
  </body>
</html>

api/main/templates/login.html
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <style>
      body {
        font-family: 'Roboto', Arial;
        background-color: #f2f2f2;
        font-size: 1rem;
      }
      h1 {
        text-align: center;
        color: #333;
      }
      form {
        background-color: #fff;
        border-radius: 5px;
        padding: 20px;
        width: 50%;
        margin: 0 auto;
      }
      label {
        display: block;
        margin-bottom: 5px;
        color: #333;
      }
      input[type="text"],
      input[type="password"] {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-bottom: 10px;
      }
      input[type="checkbox"] {
        margin-right: 5px;
      }
      input[type="submit"] {
        background-color: #4CAF50;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 6px;
        cursor: pointer;
      }
      input[type="submit"]:hover {
        background-color: #45a049;
      }
      .error {
        color: red;
      }
    </style>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&family=Roboto&display=swap" rel="stylesheet">
  </head>
  <body>
    <h1>Login</h1>
    <form method="POST" action="{{ url_for('auth.login') }}">
      {{ form.csrf_token }}
      <label for="username">Username:</label>
      {{ form.username(size=30) }}
      {% for error in form.username.errors %}
        <p class="error">{{ error }}</p>
      {% endfor %}
      <label for="password">Password:</label>
      {{ form.password(size=30) }}
      {% for error in form.password.errors %}
        <p class="error">{{ error }}</p>
      {% endfor %}
      <label>
        <input type="checkbox" name="remember_me"> Keep me logged in
      </label>
      <input type="submit" value="Login">
    </form>
  </body>
</html>

api/main/templates/profile.html
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio Manager - Profile</title>
    <style>
      body {
        font-family: 'Roboto', Arial;
        background-color: #f2f2f2;
        font-size: 1.5rem;
      }
      h1 {
        text-align: center;
        color: #333;
        font-size: 3rem;
        margin-top: 2rem;
      }
      p {
        font-size: 1.2rem;
        line-height: 1.5;
        margin-bottom: 1.5rem;
      }
      a {
        color: #4CAF50;
        text-decoration: none;
        font-weight: bold;
      }
      a:hover {
        text-decoration: underline;
      }
      form {
        background-color: #fff;
        border-radius: 5px;
        padding: 20px;
        width: 50%;
        margin: 0 auto;
      }
      label {
        display: block;
        margin-bottom: 5px;
        color: #333;
      }
      input[type="text"],
      input[type="password"],
      input[type="email"] {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-bottom: 10px;
      }
      input[type="submit"] {
        background-color: #4CAF50;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 6px;
        cursor: pointer;
      }
      input[type="submit"]:hover {
        background-color: #45a049;
      }
      .error {
        color: red;
      }
    </style>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&family=Roboto&display=swap" rel="stylesheet">
  </head>
  <body>
    <h1>Portfolio Manager</h1>
    <p>Welcome to your profile, {{ user.name }} {{ user.surname }}!</p>
    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Password: **********</p>
    <a href="{{ url_for('auth.logout')  }}">logout</a>
  </body>
</html>

api/main/templates/register.html
<!DOCTYPE html>
<html>
  <head>
    <title>Register</title>
    <style>
      body {
        font-family: 'Roboto', Arial;
        background-color: #f2f2f2;
        font-size: 1.5rem;
      }
      h1 {
        text-align: center;
        color: #333;
      }
      form {
        background-color: #fff;
        border-radius: 5px;
        padding: 20px;
        width: 50%;
        margin: 0 auto;
      }
      label {
        display: block;
        margin-bottom: 5px;
        color: #333;
      }
      input[type="text"],
      input[type="email"],
      input[type="password"] {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-bottom: 10px;
      }
      input[type="submit"] {
        background-color: #4CAF50;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 6px;
        cursor: pointer;
      }
      input[type="submit"]:hover {
        background-color: #45a049;
      }
      .error {
        color: red;
      }
    </style>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&family=Roboto&display=swap" rel="stylesheet">
  </head>
  <body>
    <h1>Register</h1>
    <form method="POST" action="{{ url_for('auth.register') }}">
      {{ form.csrf_token }}
      <label for="email">Email:</label>
      {{ form.email(size=30) }}
      {% for error in form.email.errors %}
        <p class="error">{{ error }}</p>
      {% endfor %}
      <label for="username">Username:</label>
      {{ form.username(size=30) }}
      {% for error in form.username.errors %}
        <p class="error">{{ error }}</p>
      {% endfor %}
      <label for="password">Password:</label>
      {{ form.password(size=30) }}
      {% for error in form.password.errors %}
        <p class="error">{{ error }}</p>
      {% endfor %}
      <label for="confirm_password">Confirm Password:</label>
      {{ form.confirm_password(size=30) }}
      {% for error in form.confirm_password.errors %}
        <p class="error">{{ error }}</p>
      {% endfor %}
      <label for="name">Name:</label>
      {{ form.name(size=30) }}
      {% for error in form.name.errors %}
        <p class="error">{{ error }}</p>
      {% endfor %}
      <label for="surname">Surname:</label>
      {{ form.surname(size=30) }}
      {% for error in form.surname.errors %}
        <p class="error">{{ error }}</p>
      {% endfor %}
      <input type="submit" value="Register">
    </form>
  </body>
</html>

api/main/templates/unconfirmed.html
<!DOCTYPE html>
<html>
  <head>
    <title>Email Confirmation Required</title>
    <style>
      body {
        font-family: 'Roboto', Arial;
        background-color: #f2f2f2;
        font-size: 1.5rem;
      }
      h1 {
        text-align: center;
        color: #333;
        font-size: 3rem;
        margin-top: 2rem;
      }
      p {
        font-size: 1.2rem;
        line-height: 1.5;
        margin-bottom: 1.5rem;
      }
      a {
        color: #4CAF50;
        text-decoration: none;
        font-weight: bold;
      }
      a:hover {
        text-decoration: underline;
      }
      form {
        background-color: #fff;
        border-radius: 5px;
        padding: 20px;
        width: 50%;
        margin: 0 auto;
      }
      label {
        display: block;
        margin-bottom: 5px;
        color: #333;
      }
      input[type="text"],
      input[type="password"],
      input[type="email"] {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-bottom: 10px;
      }
      input[type="submit"] {
        background-color: #4CAF50;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 6px;
        cursor: pointer;
      }
      input[type="submit"]:hover {
        background-color: #45a049;
      }
      .error {
        color: red;
      }
    </style>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&family=Roboto&display=swap" rel="stylesheet">
  </head>
  <body>
    <h1>Email Confirmation Required</h1>
    <p>Please confirm your email address to access this page.</p>
    <p>If you have not received a confirmation email, please check your spam folder or <a href="{{ url_for('auth.resend') }}">resend confirmation email</a>.</p>
    <p>If you continue to have issues, please contact support at <a href="mailto:support@example.com">support@example.com</a>.</p>
  </body>
</html>